### ISSUE TITLE
Todo App spring 프로젝트 생성

### ISSUE THREAD

**Issue by jujang** [jujang/TodoApp#1]
### 만들고자 하는 것이 무엇인가요?
TodoApp project

### 해당 프로젝트를 위해 할 일이 무엇인가요?
1. [x] spring initializr에서 프로젝트 다운
2. [x] 요구 버전에 맞게 build.gradle 파일 수정
3. [x] controller get 메서드 생성

### 예상 작업 시간
0.5h
