### ISSUE TITLE
Todo App 깃허브 레포지토리 생성

### ISSUE THREAD

**Issue by jujang** [jujang/TodoApp#2]
### 만들고자 하는 것이 무엇인가요?
TodoApp 깃허브 레포지토리

### 해당 작업을 위해 할 일이 무엇인가요?
1. [x] 깃허브 레포지토리 생성
2. [x] .gitignore, README.md, License.txt 생성 설정
3. [x] 로컬 프로젝트와 깃 연결

### 예상 작업 시간
0.5h
